language: cpp

dist: bionic

install:
  - sudo apt-get update
  - sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib mc openocd build-essential

script:
  - mkdir build
  - cd build/
  - cmake ..
  - make

after_failure:
  - cat CMakeFiles/CMakeOutput.log

notifications:
  slack:
    secure: f3eY5dz47Z9Q9whNdMCIz5cW17H7wC74CYL//QPLRuyyxjva4bvDW1h9W8zCgHKGNrmb5I41K5Voy5Pjy42s3RKJpeVvmjD/rukq3rZ9Fy4ljSuwW3IuBP/6ew3rqWtRYoZFI3Q9idWDV8zMrL+pybQHxk0JR/gYZVcuRRXm840=
